[package]
name = "reth-cosmos-dev"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false

[dependencies]
eyre = "0.6"
alloy-primitives = "=1.6.1"
cosmos-auth = { path = "crates/cosmos-auth" }
jsonrpsee = { version = "0.26", features = ["server"] }
tokio = { version = "1", features = ["sync"] }
reth-ethereum = { path = "vendor/reth/crates/ethereum/reth", features = ["node", "cli", "consensus"] }
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
alloy-consensus = { version = "=2.1.1", features = ["k256", "serde"] }
alloy-eips = "=2.1.1"
alloy-genesis = "=2.1.1"
alloy-rlp = "0.3"
k256 = { version = "0.13", features = ["ecdsa"] }
reth-codecs = "=0.5.2"
serde_json = "1"

[profile.dev]
debug = 0

[profile.dev.package.reth-cosmos-dev]
opt-level = 1

[profile.test]
debug = 0

[workspace]
members = ["crates/cosmos-auth"]
exclude = ["vendor/reth"]

[patch.crates-io]
alloy-consensus = { path = "vendor/alloy-consensus" }
alloy-evm = { path = "vendor/alloy-evm" }
reth-codecs = { path = "vendor/reth-codecs" }
alloy-rpc-types-eth = { path = "vendor/alloy-rpc-types-eth" }
alloy-network = { path = "vendor/alloy-network" }
